FROM scratch
MAINTAINER \
[Adam Miller <maxamillion@fedoraproject.org>] \
[Patrick Uiterwijk <patrick@puiterwijk.org>]
ENV DISTTAG=frawhidecontainer FGC=frawhide FBR=frawhide
ADD fedora-rawhide-armhfp-20180303.tar.xz /
